Settings:
  passwordProtected: true

  Password: "winterDorf2024"

  time-until-kick: 60
  amounts-of-tries: 3
  # How long the player should be banned in days
  banned-time: 60

  # If the player should be teleported to a location when he joins the server
  teleport-to-location:
    onJoin:
      enabled: true
      # If worldSpawn is set to true, the player will be teleported to the world spawn and the location will be ignored
      worldSpawn: true
      # The location should be set in the following format: world,x,y,z,yaw,pitch
      location: world,-122,76,-144,0,0
    onPasswordCorrect:
      enabled: false
      # If worldSpawn is set to true, the player will be teleported to the world spawn and the location will be ignored
      worldSpawn: false
      # The location should be set in the following format: world,x,y,z,yaw,pitch
      location: world,-122,96,-144,0,0

  Countdown-Settings:
    countdown: true
    # Write the time in seconds when the player should get a countdown message
    # The Time is meant to be the time until the player gets kicked
    # Example if the time-until-kick is 60, and there is a countdown-timing in here for 10 seconds, the player will get a countdown message after 50 seconds
    # The countdown-timing numbers should be separated by a comma
    countdown-timing: 30, 15, 10, 5, 4, 3, 1, 2
    # As a placeholder for the time until the player gets kicked, use %time%
    countdown-messages-template: "§4 Du hast noch %time% Sekunden"


  # For colors use the following format: §<color-code>
  # For a list of color codes visit: https://minecraft.gamepedia.com/Formatting_codes
  # To use the § symbol in the config file, type Alt Gr + 5
  Welcome-Message:
    title: "§b Winterdorf"
    sub-title: "§4 Bitte geben Sie §2 das Passwort ein"

    chat-message:
      - 1:
        message: "Du hast 60 Sekunden Zeit, das Passwort einzugeben"
      - 2:
        message: "Gib das Password mittels dem Command §c/password §rein"